version: '3.8'

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      # Basic Configuration
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANSCHEDULE: "*/5 * * * *"  # Scan every 5 minutes
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      
      # Performance optimizations for Pi 5
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_IMAGESIZE: 300
      ND_COVERARTPRIORITY: "embedded, cover.*, folder.*, front.*"
      
      # Enable downloads (Spotify Premium-like feature)
      ND_ENABLEDOWNLOADS: "true"
      ND_ENABLESHARING: "true"
      
      # UI Customizations
      ND_UIWELCOMEMESSAGE: "Welcome to Your Personal Music Server!"
      ND_UILOGINBACKGROUNDURL: ""
      
      # Performance settings for Raspberry Pi
      ND_TRANSCODINGCACHESIZE: 50MB
      ND_MAXSIDEBARPLAYLISTS: 100
    volumes:
      - /home/pi/music:/music:ro
      - navidrome_data:/data
      - ./config/navidrome:/var/lib/navidrome
    networks:
      - music_network
    
    # Resource limits for Pi 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # Optional: Web interface for manual downloads
  youtube_downloader:
    build: ./web
    container_name: youtube_downloader
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /home/pi/music:/downloads
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - DOWNLOAD_PATH=/downloads
      - LOG_LEVEL=INFO
    networks:
      - music_network
    depends_on:
      - navidrome

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: music_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static:/usr/share/nginx/html:ro
    networks:
      - music_network
    depends_on:
      - navidrome
      - youtube_downloader

volumes:
  navidrome_data:

networks:
  music_network:
    driver: bridge
